### ISSUE TITLE
Error while running send2trash on Python 3.7.0 beta 2

### ISSUE THREAD

**Issue by victordomingos** [hsoft/send2trash#24]
I have a small script that uses send2trash and works very well in Python 3.6 (Mac OS X 10.11 El Capitan). However, when I try to run it in Python 3.7.0 beta 2, it fails with the traceback bellow.

best regards,
victor

```
Traceback (most recent call last):
  File "/Users/fact/Dropbox/Aplicativos/Filemaker_backups/NPK-Backup/remove_old_archives.py", line 26, in <module>
    from send2trash import send2trash
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/send2trash/__init__.py", line 12, in <module>
    from .plat_osx import send2trash
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/send2trash/plat_osx.py", line 17, in <module>
    GetMacOSStatusCommentString = Foundation.GetMacOSStatusCommentString
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 369, in __getattr__
    func = self.__getitem__(name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 374, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(RTLD_DEFAULT, GetMacOSStatusCommentString): symbol not found
```

**Comment by mingwandroid** [comment]
Bug is: https://bugs.python.org/issue33281

**Comment by yblock** [comment]
This seems to be happening again

**Comment by davidcarnahan** [comment]
I can confirm the same ... same script works on my windows computer but does not work on my macOs that I just updated with Big Sur. 

Traceback (most recent call last):
  File "cleanup.py", line 4, in <module>
    from send2trash import send2trash
  File "/usr/local/lib/python3.7/site-packages/send2trash/__init__.py", line 12, in <module>
    from .plat_osx import send2trash
  File "/usr/local/lib/python3.7/site-packages/send2trash/plat_osx.py", line 17, in <module>
    GetMacOSStatusCommentString = Foundation.GetMacOSStatusCommentString
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 369, in __getattr__
    func = self.__getitem__(name)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 374, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(RTLD_DEFAULT, GetMacOSStatusCommentString): symbol not found

**Comment by BoboTiG** [comment]
Let's wait for Python 3.8.9 and 3.9.1 and retry then. I am afraid that this will never work for 3.6 and 3.7 because it is not planned to backport macOS Big Sur support on it.

**Comment by BoboTiG** [comment]
As an alternative, I am using this code if that helps:  https://github.com/nuxeo/nuxeo-drive/blob/master/nxdrive/client/local/darwin.py#L119-L150

**Comment by HWiese1980** [comment]
Is this issue solved? I'm still seeing it with send2trash 1.5.0 (from PyPi)

**Comment by HWiese1980** [comment]
@arsenetar Is this issue solved? Is there a fix/workaround?

**Comment by arsenetar** [comment]
@HWiese1980 I was not fully aware this was an ongoing issue, I am aware of several potential ways to solve the issue.  It is not currently fixed here with respect to MacOS Big Sur.

**Comment by arsenetar** [comment]
All conversation on the Big Sur related issue that is open should continue over at #51
